/**
 * `createPostgresStore` — a Postgres-backed `MetadataStore`.
 *
 * Built on `pg` (node-postgres). Public methods are async (the
 * interface requires it); the actual SQL runs against a `Pool`
 * whose connections are managed internally.
 *
 * Schema (one table):
 *
 *   nodes(
 *     id          UUID PRIMARY KEY,        -- generated by the app
 *     tenant_id   TEXT NOT NULL,
 *     parent_id   UUID,                    -- NULL = root
 *     name        TEXT NOT NULL,
 *     path        TEXT NOT NULL,           -- materialized "/a/b/c"
 *     kind        TEXT NOT NULL CHECK (kind IN ('file','folder')),
 *     size        BIGINT NOT NULL DEFAULT 0,
 *     mime_type   TEXT NOT NULL DEFAULT '',
 *     s3_key      TEXT NOT NULL DEFAULT '',
 *     owner_id    TEXT NOT NULL,
 *     metadata    JSONB NOT NULL DEFAULT '{}'::jsonb,
 *     created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
 *     updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
 *     deleted_at  TIMESTAMPTZ
 *   )
 *
 * Two partial unique indexes for name uniqueness (Postgres treats
 * NULL as distinct in UNIQUE indexes, same footgun as SQLite):
 *
 *   - (tenant_id, parent_id, name) WHERE deleted_at IS NULL
 *     AND parent_id IS NOT NULL  → non-root siblings
 *   - (tenant_id, name) WHERE deleted_at IS NULL
 *     AND parent_id IS NULL      → root children
 *
 * Indexes for hot paths:
 *   nodes_path_prefix  → LIKE 'path/%' for moveNode cascade
 *   nodes_tenant_parent → listChildren
 *   nodes_name_lower   → btree on lower(name); used for exact-match
 *                        LIKE/ILIKE plans (no leading wildcard)
 *   nodes_name_trgm_idx → GIN trigram on lower(name); used for
 *                         ILIKE '%x%' plans (leading wildcard).
 *                         Requires CREATE EXTENSION pg_trgm.
 *
 * Tenant isolation is enforced in app code (every query filters
 * by tenant_id). For a stricter setup, RLS policies + a per-query
 * `SET LOCAL app.current_tenant` would close the gap at the DB.
 * Tracked for a follow-up.
 *
 * The `reconcile()` method is a no-op scan — same as the memory
 * and SQLite stores. Real bucket-walking reconcile would need
 * the S3 adapter injected into the store, which would change the
 * interface. Deferred to a follow-up.
 */
import { createRequire } from "node:module";
import type { Pool, PoolClient, QueryResultRow } from "pg";

/**
 * Lazy-load `pg` (node-postgres). The native modules (pg's optional
 * native bindings) and connection management shouldn't enter
 * every consumer's bundle. Same pattern as `sqlite-store.ts`.
 */
type PgModule = typeof import("pg");
type PgTypes = {
  Pool: new (opts: { connectionString: string; max?: number }) => Pool;
  PoolClient: new (...args: never[]) => PoolClient;
  QueryResultRow: QueryResultRow;
};
const extractPg = (mod: PgModule): PgTypes => {
  const m = mod as unknown as { default?: PgTypes };
  return m.default ?? (mod as unknown as PgTypes);
};
import {
  err,
  ok,
  type Result,
} from "@/types/result";
import { FileSystemError } from "@/errors";
import { asS3Key, asTenantId, asUserId } from "@/types/branded";
import type { TenantId } from "@/types/branded";
import { sanitizeLikePattern } from "./sanitize";
import { decodeCursor, pageCursor } from "./cursor";
import { normalizeNodeName } from "./node-name";
import type {
  CreateNodeInput,
  DeleteNodeInput,
  FileNode,
  GetNodeInput,
  GetPathInput,
  ListChildrenInput,
  ListChildrenOutput,
  MetadataStore,
  MoveNodeInput,
  ReconcileResult,
  SearchInput,
  UpdateMetadataInput,
} from "./store";

// ---------------------------------------------------------------------------
// Options
// ---------------------------------------------------------------------------

export interface PostgresStoreOptions {
  /**
   * A libpq connection string. Example:
   *   postgres://user:pass@localhost:5432/dbname
   */
  readonly connectionString: string;
  /**
   * Postgres schema (namespace). Defaults to "public".
   * Use a dedicated schema per tenant in shared clusters.
   */
  readonly schema?: string;
  /**
   * Run schema migrations on construction. Default: true.
   */
  readonly runMigrations?: boolean;
  /**
   * Max pool size. Defaults to 10.
   */
  readonly maxPoolSize?: number;
}

// ---------------------------------------------------------------------------
// Row → FileNode
// ---------------------------------------------------------------------------

interface NodeRow extends QueryResultRow {
  readonly id: string;
  readonly tenant_id: string;
  readonly parent_id: string | null;
  readonly name: string;
  readonly path: string;
  readonly kind: "file" | "folder";
  readonly size: string | number;
  readonly mime_type: string;
  readonly s3_key: string;
  readonly owner_id: string;
  readonly metadata: Record<string, string>;
  readonly created_at: Date;
  readonly updated_at: Date;
  readonly deleted_at: Date | null;
}

interface OrphanRow {
  readonly id: string;
  readonly tenant_id: string;
  readonly s3_key: string;
  readonly metadata_id: string | null;
  readonly reason: string;
  readonly created_at: Date;
}

const rowToPendingOrphan = (row: OrphanRow) => ({
  id: row.id,
  tenantId: asTenantId(row.tenant_id),
  s3Key: asS3Key(row.s3_key),
  metadataId: row.metadata_id,
  reason: row.reason,
  createdAt: row.created_at,
});

const rowToFileNode = (row: NodeRow): FileNode => ({
  id: row.id,
  tenantId: asTenantId(row.tenant_id),
  parentId: row.parent_id,
  name: row.name,
  path: row.path,
  kind: row.kind,
  // pg returns BIGINT as string by default to avoid precision loss
  // on JS numbers > 2^53. Cast back; file sizes fit comfortably.
  size: typeof row.size === "string" ? Number.parseInt(row.size, 10) : row.size,
  mimeType: row.mime_type,
  s3Key: row.s3_key,
  ownerId: asUserId(row.owner_id),
  metadata: row.metadata,
  createdAt: row.created_at,
  updatedAt: row.updated_at,
  deletedAt: row.deleted_at,
});

// ---------------------------------------------------------------------------
// Migrations
// ---------------------------------------------------------------------------

const SCHEMA_VERSION = 3;

const MIGRATION_SQL = (schema: string): string => `
-- pg_trgm provides the gin_trgm_ops operator class so we can build
-- a GIN trigram index on lower(name). Without the extension,
-- CREATE INDEX … USING GIN (lower(name) gin_trgm_ops) fails.
-- The extension is shared across the cluster (no schema), so it
-- only needs to be installed once per database. IF NOT EXISTS
-- makes the call a no-op on subsequent migrations.
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE SCHEMA IF NOT EXISTS "${schema}";

-- Tables are schema-qualified (they have to be, to live in
-- the schema). Index NAMES must NOT be schema-qualified —
-- Postgres syntax error otherwise. The index inherits the
-- schema from its table, so search_path isn't required.

CREATE TABLE IF NOT EXISTS "${schema}".schema_meta (
  key   TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "${schema}".nodes (
  id          UUID PRIMARY KEY,
  tenant_id   TEXT NOT NULL,
  parent_id   UUID,
  name        TEXT NOT NULL,
  path        TEXT NOT NULL,
  kind        TEXT NOT NULL CHECK (kind IN ('file', 'folder')),
  size        BIGINT NOT NULL DEFAULT 0,
  mime_type   TEXT NOT NULL DEFAULT '',
  s3_key      TEXT NOT NULL DEFAULT '',
  owner_id    TEXT NOT NULL,
  metadata    JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at  TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "${schema}".pending_orphans (
  id          UUID PRIMARY KEY,
  tenant_id   TEXT NOT NULL,
  s3_key      TEXT NOT NULL,
  metadata_id TEXT,
  reason      TEXT NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS pending_orphans_tenant_created
  ON "${schema}".pending_orphans (tenant_id, created_at);

-- Name uniqueness for non-root siblings.
CREATE UNIQUE INDEX IF NOT EXISTS nodes_unique_live_nonroot_name
  ON "${schema}".nodes (tenant_id, parent_id, name)
  WHERE deleted_at IS NULL AND parent_id IS NOT NULL;

-- Name uniqueness for root children (NULL parent_id).
CREATE UNIQUE INDEX IF NOT EXISTS nodes_unique_live_root_name
  ON "${schema}".nodes (tenant_id, name)
  WHERE deleted_at IS NULL AND parent_id IS NULL;

CREATE INDEX IF NOT EXISTS nodes_path_prefix
  ON "${schema}".nodes (path text_pattern_ops);
CREATE INDEX IF NOT EXISTS nodes_tenant_parent
  ON "${schema}".nodes (tenant_id, parent_id);
CREATE INDEX IF NOT EXISTS nodes_name_lower
  ON "${schema}".nodes (lower(name));

-- GIN trigram index lets ILIKE '%foo%' on lower(name) use an
-- index plan instead of a seq scan. Cheap to maintain (~3x the
-- row size), but search is O(matches) instead of O(rows) — a
-- real win past a few thousand rows.
CREATE INDEX IF NOT EXISTS nodes_name_trgm_idx
  ON "${schema}".nodes USING GIN (lower(name) gin_trgm_ops);

CREATE TABLE IF NOT EXISTS "${schema}".shares (
  token      TEXT PRIMARY KEY,
  tenant_id  TEXT NOT NULL,
  node_id    UUID NOT NULL,
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE "${schema}".nodes ENABLE ROW LEVEL SECURITY;
ALTER TABLE "${schema}".nodes FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "${schema}".nodes;
CREATE POLICY tenant_isolation ON "${schema}".nodes
  USING (tenant_id = current_setting('app.current_tenant', true))
  WITH CHECK (tenant_id = current_setting('app.current_tenant', true));

ALTER TABLE "${schema}".pending_orphans ENABLE ROW LEVEL SECURITY;
ALTER TABLE "${schema}".pending_orphans FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS orphan_tenant_isolation ON "${schema}".pending_orphans;
CREATE POLICY orphan_tenant_isolation ON "${schema}".pending_orphans
  USING (tenant_id = current_setting('app.current_tenant', true))
  WITH CHECK (tenant_id = current_setting('app.current_tenant', true));
`;

const runMigrations = async (
  pool: Pool,
  schema: string,
): Promise<void> => {
  const client = await pool.connect();
  try {
    await client.query(MIGRATION_SQL(schema));
    await client.query(
      `INSERT INTO "${schema}".schema_meta (key, value) VALUES ('version', $1)
       ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value`,
      [String(SCHEMA_VERSION)],
    );
  } finally {
    client.release();
  }
};

// ---------------------------------------------------------------------------
// Factory
// ---------------------------------------------------------------------------

export const createPostgresStore = (
  options: PostgresStoreOptions,
): MetadataStore => {
  // Public factory is sync; the real work builds lazily on first
  // method call. See the matching comment in sqlite-store.ts.
  let inner: MetadataStore | null = null;
  let pending: Promise<MetadataStore> | null = null;

  const ensureReady = async (): Promise<MetadataStore> => {
    if (inner) return inner;
    if (!pending) {
      pending = (async () => {
        const req = createRequire(import.meta.url);
        const mod = req("pg") as PgModule;
        inner = buildInner(extractPg(mod), options);
        return inner;
      })();
    }
    return pending;
  };

  const wrap = <A extends unknown[], R>(
    method: (store: MetadataStore, ...args: A) => Promise<R>,
  ): ((...args: A) => Promise<R>) =>
    async (...args: A): Promise<R> => {
      const s = await ensureReady();
      return method(s, ...args);
    };

  return {
    createNode: wrap((s, i) => s.createNode(i)),
    getNode: wrap((s, i) => s.getNode(i)),
    listChildren: wrap((s, i) => s.listChildren(i)),
    moveNode: wrap((s, i) => s.moveNode(i)),
    deleteNode: wrap((s, i) => s.deleteNode(i)),
    purgeNode: wrap((s, i) => s.purgeNode(i)),
    updateMetadata: wrap((s, i) => s.updateMetadata(i)),
    search: wrap((s, i) => s.search(i)),
    getPath: wrap((s, i) => s.getPath(i)),
    reconcile: wrap((s) => s.reconcile()),
    enqueueOrphan: wrap((s, i) => s.enqueueOrphan(i)),
    listPendingOrphans: wrap((s, i) => s.listPendingOrphans(i)),
    deleteOrphan: wrap((s, i) => s.deleteOrphan(i)),
    restoreNode: wrap((s, i) => s.restoreNode(i)),
    listTrash: wrap((s, i) => s.listTrash(i)),
    scanFileKeys: wrap((s, i) => s.scanFileKeys(i)),
    sumSize: wrap((s, i) => s.sumSize(i)),
    findByS3Key: wrap((s, i) => s.findByS3Key(i)),
    createShare: wrap((s, i) => s.createShare(i)),
    resolveShare: wrap((s, i) => s.resolveShare(i)),
    revokeShare: wrap((s, i) => s.revokeShare(i)),
  };
};

/**
 * Real factory — builds the prepared-query store using the loaded
 * pg module.
 */
const buildInner = (pg: PgTypes, options: PostgresStoreOptions): MetadataStore => {
  const pool = new pg.Pool({
    connectionString: options.connectionString,
    max: options.maxPoolSize ?? 10,
  });
  const schema = options.schema ?? "public";

  // Lazy migrations on first method call — keeps the factory
  // synchronous (the MetadataStore contract is async per method).
  let initPromise: Promise<void> | null = null;
  const ensureInitialized = async (): Promise<void> => {
    if (!initPromise) {
      initPromise =
        options.runMigrations === false
          ? Promise.resolve()
          : runMigrations(pool, schema);
    }
    return initPromise;
  };

  // -------------------------------------------------------------------------
  // Helpers
  // -------------------------------------------------------------------------

  const makeId = (): string => {
    if (typeof globalThis.crypto?.randomUUID === "function") {
      return globalThis.crypto.randomUUID();
    }
    return `pg-${Date.now()}-${Math.random().toString(36).slice(2, 10)}`;
  };

  const notFound = (id: string): Result<never, FileSystemError> =>
    err(
      new FileSystemError({
        code: "NotFound",
        message: `Node ${id} not found`,
        retryable: false,
      }),
    );

  // LIKE escape helper kept for any future ad-hoc LIKE; the
  // sanitizer in `./sanitize` is the canonical version (it has
  // unit tests and is shared with the SQLite adapter's intent
  // for FTS5).
  const escapeLike = sanitizeLikePattern;

  // Wrap a query in a transaction. Caller provides the work as an
  // async function; on success the tx commits, on throw it rolls back.
  const withTenant = async <T>(
    tenantId: string,
    fn: (c: PoolClient) => Promise<T>,
  ): Promise<T> => {
    const client = await pool.connect();
    try {
      await client.query("BEGIN");
      await client.query(`SELECT set_config('app.current_tenant', $1, true)`, [
        tenantId,
      ]);
      const result = await fn(client);
      await client.query("COMMIT");
      return result;
    } catch (e) {
      await client.query("ROLLBACK").catch(() => {
        // Ignore rollback errors — the original error is more useful.
      });
      throw e;
    } finally {
      client.release();
    }
  };

  const q = <T extends QueryResultRow>(
    tenantId: string,
    text: string,
    params: unknown[] = [],
  ) => withTenant(tenantId, (c) => c.query<T>(text, params));

  const withTx = async <T>(
    tenantId: string,
    fn: (c: PoolClient) => Promise<T>,
  ): Promise<T> => withTenant(tenantId, fn);

  // -------------------------------------------------------------------------
  // 9-method contract
  // -------------------------------------------------------------------------

  return {
    async createNode(
      input: CreateNodeInput,
    ): Promise<Result<FileNode, FileSystemError>> {
      await ensureInitialized();
      const normalized = normalizeNodeName(input.name);
      if (!normalized.ok) return normalized;
      const name = normalized.value;
      // Look up parent (if any) to compute the path. We require
      // a LIVE parent; tombstoned parents can't have new children.
      // `!= null` so BOTH null and undefined skip the lookup.
      let parentPath: string | null = null;
      if (input.parentId != null) {
        const parentRes = await q<NodeRow>(input.tenantId,
          `SELECT * FROM "${schema}".nodes
           WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL`,
          [input.parentId, input.tenantId],
        );
        const parent = parentRes.rows[0];
        if (!parent) return notFound(input.parentId);
        if (parent.kind !== "folder") {
          return err(
            new FileSystemError({
              code: "Conflict",
              message: `Parent ${input.parentId} is not a folder`,
              retryable: false,
            }),
          );
        }
        parentPath = parent.path;
      }

      const id = input.id ?? makeId();
      const path = parentPath === null ? `/${name}` : `${parentPath}/${name}`;

      try {
        await q(input.tenantId,
          `INSERT INTO "${schema}".nodes (
            id, tenant_id, parent_id, name, path, kind, size, mime_type,
            s3_key, owner_id, metadata
          ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11::jsonb)`,
          [
            id,
            input.tenantId,
            input.parentId,
            name,
            path,
            input.kind,
            input.kind === "folder" ? 0 : input.size,
            input.kind === "folder" ? "" : input.mimeType,
            input.kind === "folder" ? "" : input.s3Key,
            input.ownerId,
            JSON.stringify(input.metadata ?? {}),
          ],
        );
      } catch (e) {
        if (e instanceof Error && /nodes_unique_live/.test(e.message)) {
          return err(
            new FileSystemError({
              code: "Conflict",
              message: `A node named '${name}' already exists in this folder`,
              retryable: false,
            }),
          );
        }
        return err(
          new FileSystemError({
            code: "InternalError",
            message: `createNode failed: ${(e as Error).message}`,
            retryable: false,
          }),
        );
      }

      const created = await q<NodeRow>(input.tenantId,
        `SELECT * FROM "${schema}".nodes WHERE id = $1 AND tenant_id = $2`,
        [id, input.tenantId],
      );
      if (created.rows.length === 0) {
        return err(
          new FileSystemError({
            code: "InternalError",
            message: "Row missing immediately after insert",
            retryable: false,
          }),
        );
      }
      return ok(rowToFileNode(created.rows[0]!));
    },

    async getNode(
      input: GetNodeInput,
    ): Promise<Result<FileNode | null, FileSystemError>> {
      await ensureInitialized();
      const res = await q<NodeRow>(input.tenantId,
        `SELECT * FROM "${schema}".nodes
         WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL`,
        [input.id, input.tenantId],
      );
      return ok(res.rows[0] ? rowToFileNode(res.rows[0]) : null);
    },

    async listChildren(
      input: ListChildrenInput,
    ): Promise<Result<ListChildrenOutput, FileSystemError>> {
      await ensureInitialized();
      const limit = input.limit ?? 1000;
      const cursor = decodeCursor(input.cursor);
      const res = cursor
        ? await q<NodeRow>(
            input.tenantId,
            `SELECT * FROM "${schema}".nodes
             WHERE tenant_id = $1 AND parent_id IS NOT DISTINCT FROM $2
               AND deleted_at IS NULL
               AND (lower(name) > lower($3) OR (lower(name) = lower($3) AND id::text > $4))
             ORDER BY lower(name) ASC, id ASC
             LIMIT $5`,
            [input.tenantId, input.parentId, cursor.n, cursor.i, limit],
          )
        : await q<NodeRow>(
            input.tenantId,
            `SELECT * FROM "${schema}".nodes
             WHERE tenant_id = $1 AND parent_id IS NOT DISTINCT FROM $2
               AND deleted_at IS NULL
             ORDER BY lower(name) ASC, id ASC
             LIMIT $3`,
            [input.tenantId, input.parentId, limit],
          );
      const items = res.rows.map(rowToFileNode);
      return ok({
        items,
        nextCursor: pageCursor(items, limit),
      });
    },

    async moveNode(
      input: MoveNodeInput,
    ): Promise<Result<FileNode, FileSystemError>> {
      await ensureInitialized();
      const currentRes = await q<NodeRow>(input.tenantId,
        `SELECT * FROM "${schema}".nodes
         WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL`,
        [input.id, input.tenantId],
      );
      const current = currentRes.rows[0];
      if (!current) return notFound(input.id);

      const normalized = normalizeNodeName(input.newName ?? current.name);
      if (!normalized.ok) return normalized;
      const newName = normalized.value;

      // Validate the new parent (if any). `!= null` (NOT `!== null`)
      // so both null and undefined skip the block.
      let newParentPath: string | null = null;
      if (input.newParentId != null) {
        if (input.newParentId === current.id) {
          return err(
            new FileSystemError({
              code: "Conflict",
              message: "Cannot move a folder into itself",
              retryable: false,
            }),
          );
        }
        const newParentRes = await q<NodeRow>(input.tenantId,
          `SELECT * FROM "${schema}".nodes
           WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL`,
          [input.newParentId, input.tenantId],
        );
        const newParent = newParentRes.rows[0];
        if (!newParent) return notFound(input.newParentId);
        if (newParent.kind !== "folder") {
          return err(
            new FileSystemError({
              code: "Conflict",
              message: `Destination ${input.newParentId} is not a folder`,
              retryable: false,
            }),
          );
        }
        // Cycle: newParent must not be a descendant of current.
        if (
          newParent.path === current.path ||
          newParent.path.startsWith(`${current.path}/`)
        ) {
          return err(
            new FileSystemError({
              code: "Conflict",
              message: "Cannot move a folder into its own descendant",
              retryable: false,
            }),
          );
        }
        newParentPath = newParent.path;
      }

      const newPath =
        newParentPath === null ? `/${newName}` : `${newParentPath}/${newName}`;

      try {
        await withTx(input.tenantId, async (client) => {
          await client.query(
            `UPDATE "${schema}".nodes
             SET parent_id = $1, name = $2, path = $3, updated_at = now()
             WHERE id = $4`,
            [input.newParentId, newName, newPath, input.id],
          );
          if (current.path !== newPath) {
            // Prefix-only replace via substring — same trick as
            // the SQLite store, but using Postgres substring()
            // (1-indexed). SUBSTR's LENGTH on the old path + 1
            // gives the position of the leading '/' in the
            // descendant path.
            await client.query(
              `UPDATE "${schema}".nodes
               SET path = $1 || substring(path FROM length($2) + 1),
                   updated_at = now()
               WHERE path LIKE $2 || '/%'`,
              [newPath, current.path],
            );
          }
        });
      } catch (e) {
        if (e instanceof Error && /nodes_unique_live/.test(e.message)) {
          return err(
            new FileSystemError({
              code: "Conflict",
              message: `A node named '${newName}' already exists in the destination folder`,
              retryable: false,
            }),
          );
        }
        return err(
          new FileSystemError({
            code: "InternalError",
            message: `moveNode failed: ${(e as Error).message}`,
            retryable: false,
          }),
        );
      }

      const updated = await q<NodeRow>(input.tenantId,
        `SELECT * FROM "${schema}".nodes
         WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL`,
        [input.id, input.tenantId],
      );
      if (updated.rows.length === 0) {
        return err(
          new FileSystemError({
            code: "InternalError",
            message: "Node missing after move",
            retryable: false,
          }),
        );
      }
      return ok(rowToFileNode(updated.rows[0]!));
    },

    async deleteNode(
      input: DeleteNodeInput,
    ): Promise<Result<void, FileSystemError>> {
      await ensureInitialized();
      const nodeRes = await q<NodeRow>(input.tenantId,
        `SELECT * FROM "${schema}".nodes
         WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL`,
        [input.id, input.tenantId],
      );
      const node = nodeRes.rows[0];
      if (!node) return notFound(input.id);

      if (node.kind === "folder" && !input.recursive) {
        const childRes = await q(input.tenantId,
          `SELECT 1 FROM "${schema}".nodes
           WHERE tenant_id = $1 AND parent_id = $2 AND deleted_at IS NULL
           LIMIT 1`,
          [input.tenantId, input.id],
        );
        if (childRes.rows.length > 0) {
          return err(
            new FileSystemError({
              code: "Conflict",
              message: `Folder '${node.name}' is not empty; pass recursive: true to delete the subtree`,
              retryable: false,
            }),
          );
        }
      }

      if (input.recursive || node.kind === "file") {
        await q(input.tenantId,
          `UPDATE "${schema}".nodes
           SET deleted_at = now(), updated_at = now()
           WHERE (id = $1 OR path LIKE $2 || '/%')
             AND deleted_at IS NULL`,
          [input.id, node.path],
        );
      } else {
        await q(input.tenantId,
          `UPDATE "${schema}".nodes
           SET deleted_at = now(), updated_at = now()
           WHERE id = $1`,
          [input.id],
        );
      }
      return ok(undefined);
    },

    async purgeNode(input: {
      tenantId: TenantId;
      id: string;
    }): Promise<Result<{ s3Keys: ReadonlyArray<string> }, FileSystemError>> {
      await ensureInitialized();
      const nodeRes = await q<{ id: string; path: string }>(input.tenantId,
        `SELECT id, path FROM "${schema}".nodes
         WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NOT NULL`,
        [input.id, input.tenantId],
      );
      const node = nodeRes.rows[0];
      if (!node) {
        return err(
          new FileSystemError({
            code: "NotFound",
            message: `Trashed node ${input.id} not found`,
            retryable: false,
          }),
        );
      }
      const like = `${node.path}/%`;
      const files = await q<{ s3_key: string }>(input.tenantId,
        `SELECT s3_key FROM "${schema}".nodes
         WHERE tenant_id = $1 AND deleted_at IS NOT NULL AND kind = 'file' AND s3_key <> ''
           AND (id = $2 OR path LIKE $3)`,
        [input.tenantId, input.id, like],
      );
      await q(input.tenantId,
        `DELETE FROM "${schema}".shares WHERE tenant_id = $1 AND node_id IN (
           SELECT id FROM "${schema}".nodes
           WHERE tenant_id = $1 AND deleted_at IS NOT NULL AND (id = $2 OR path LIKE $3)
         )`,
        [input.tenantId, input.id, like],
      );
      await q(input.tenantId,
        `DELETE FROM "${schema}".nodes
         WHERE tenant_id = $1 AND deleted_at IS NOT NULL AND (id = $2 OR path LIKE $3)`,
        [input.tenantId, input.id, like],
      );
      return ok({ s3Keys: files.rows.map((row) => row.s3_key) });
    },

    async updateMetadata(
      input: UpdateMetadataInput,
    ): Promise<Result<FileNode, FileSystemError>> {
      await ensureInitialized();
      const exists = await q(input.tenantId,
        `SELECT 1 FROM "${schema}".nodes
         WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL`,
        [input.id, input.tenantId],
      );
      if (exists.rows.length === 0) return notFound(input.id);

      // Replace or merge via JSONB concat. The `||` operator
      // merges with right-hand keys winning on conflict.
      const sql = input.replace
        ? `UPDATE "${schema}".nodes
           SET metadata = $1::jsonb, updated_at = now()
           WHERE id = $2 AND tenant_id = $3`
        : `UPDATE "${schema}".nodes
           SET metadata = metadata || $1::jsonb, updated_at = now()
           WHERE id = $2 AND tenant_id = $3`;
      await q(input.tenantId, sql, [
        JSON.stringify(input.metadata),
        input.id,
        input.tenantId,
      ]);

      const updated = await q<NodeRow>(input.tenantId,
        `SELECT * FROM "${schema}".nodes WHERE id = $1 AND tenant_id = $2`,
        [input.id, input.tenantId],
      );
      if (updated.rows.length === 0) return notFound(input.id);
      return ok(rowToFileNode(updated.rows[0]!));
    },

    async search(
      input: SearchInput,
    ): Promise<Result<ListChildrenOutput, FileSystemError>> {
      await ensureInitialized();
      const limit = input.limit ?? 100;

      // Empty query → no results (v0.2 contract). Without this,
      // `ILIKE '%%'` would match every node in the tenant.
      if (input.query.length === 0) {
        return ok({ items: [], nextCursor: undefined });
      }

      const pattern = `%${escapeLike(input.query)}%`;

      let res;
      if (input.parentId === undefined) {
        // No scope: search the whole tenant.
        res = await q<NodeRow>(input.tenantId,
          `SELECT * FROM "${schema}".nodes
           WHERE tenant_id = $1 AND deleted_at IS NULL
             AND name ILIKE $2 ESCAPE '\\'
           ORDER BY lower(name) ASC
           LIMIT $3`,
          [input.tenantId, pattern, limit],
        );
      } else {
        const parentRes = await q<NodeRow>(input.tenantId,
          `SELECT * FROM "${schema}".nodes
           WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL`,
          [input.parentId, input.tenantId],
        );
        const parent = parentRes.rows[0];
        if (!parent) return notFound(input.parentId);
        // Root's subtree is the whole tenant — use the unscoped query.
        if (parent.path === "/") {
          res = await q<NodeRow>(input.tenantId,
            `SELECT * FROM "${schema}".nodes
             WHERE tenant_id = $1 AND deleted_at IS NULL
               AND name ILIKE $2 ESCAPE '\\'
             ORDER BY lower(name) ASC
             LIMIT $3`,
            [input.tenantId, pattern, limit],
          );
        } else {
          res = await q<NodeRow>(input.tenantId,
            `SELECT * FROM "${schema}".nodes
             WHERE tenant_id = $1 AND deleted_at IS NULL
               AND (id = $2 OR path LIKE $3 || '/%')
               AND name ILIKE $4 ESCAPE '\\'
             ORDER BY lower(name) ASC
             LIMIT $5`,
            [input.tenantId, input.parentId, parent.path, pattern, limit],
          );
        }
      }
      return ok({
        items: res.rows.map(rowToFileNode),
        nextCursor: res.rows.length === limit ? String(limit) : undefined,
      });
    },

    async getPath(
      input: GetPathInput,
    ): Promise<Result<{ segments: FileNode[] }, FileSystemError>> {
      await ensureInitialized();
      // Recursive CTE walks up the parent chain in one query.
      // Includes tombstoned ancestors to match the memory/SQLite
      // behavior (no gaps even if a mid-chain parent is deleted).
      const res = await q<NodeRow>(input.tenantId,
        `WITH RECURSIVE chain AS (
           SELECT * FROM "${schema}".nodes
            WHERE id = $1 AND tenant_id = $2
           UNION ALL
           SELECT n.* FROM "${schema}".nodes n
             JOIN chain c ON n.id = c.parent_id
            WHERE n.tenant_id = $2
         )
         SELECT * FROM chain ORDER BY path ASC`,
        [input.id, input.tenantId],
      );
      if (res.rows.length === 0) return notFound(input.id);
      return ok({ segments: res.rows.map(rowToFileNode) });
    },

    async enqueueOrphan(input) {
      await ensureInitialized();
      const id = makeId();
      try {
        await q(input.tenantId,
          `INSERT INTO "${schema}".pending_orphans (
             id, tenant_id, s3_key, metadata_id, reason
           ) VALUES ($1, $2, $3, $4, $5)`,
          [
            id,
            input.tenantId,
            input.s3Key,
            input.metadataId ?? null,
            input.reason,
          ],
        );
        return ok({ id });
      } catch (error) {
        return err(FileSystemError.fromPg(error));
      }
    },

    async listPendingOrphans(input) {
      await ensureInitialized();
      try {
        const result = await q<OrphanRow>(input.tenantId,
          `SELECT * FROM "${schema}".pending_orphans
           WHERE tenant_id = $1
           ORDER BY created_at ASC, id ASC`,
          [input.tenantId],
        );
        return ok(result.rows.map(rowToPendingOrphan));
      } catch (error) {
        return err(FileSystemError.fromPg(error));
      }
    },

    async deleteOrphan(input) {
      await ensureInitialized();
      try {
        const result = await q(input.tenantId,
          `DELETE FROM "${schema}".pending_orphans
           WHERE tenant_id = $1 AND id = $2`,
          [input.tenantId, input.id],
        );
        if (result.rowCount === 0) {
          return err(
            new FileSystemError({
              code: "NotFound",
              message: `Orphan ${input.id} not found`,
              retryable: false,
            }),
          );
        }
        return ok(undefined);
      } catch (error) {
        return err(FileSystemError.fromPg(error));
      }
    },

    async reconcile(): Promise<Result<ReconcileResult, FileSystemError>> {
      await ensureInitialized();
      return ok({ orphansInStore: [], orphansInS3: [], scanned: 0 });
    },

    async restoreNode(input) {
      await ensureInitialized();
      try {
        const res = await q<NodeRow>(
          input.tenantId,
          `UPDATE "${schema}".nodes
           SET deleted_at = NULL, updated_at = now()
           WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NOT NULL
           RETURNING *`,
          [input.id, input.tenantId],
        );
        if (!res.rows[0]) return notFound(input.id);
        return ok(rowToFileNode(res.rows[0]));
      } catch (e) {
        if (e instanceof Error && /nodes_unique_live/.test(e.message)) {
          return err(
            new FileSystemError({
              code: "Conflict",
              message: "A live node with this name already exists in the folder",
              retryable: false,
            }),
          );
        }
        return err(FileSystemError.fromPg(e));
      }
    },

    async listTrash(input) {
      await ensureInitialized();
      const limit = input.limit ?? 1000;
      const cursor = decodeCursor(input.cursor);
      const res = cursor
        ? await q<NodeRow>(
            input.tenantId,
            `SELECT * FROM "${schema}".nodes
             WHERE tenant_id = $1 AND deleted_at IS NOT NULL
               AND (lower(name) > lower($2) OR (lower(name) = lower($2) AND id::text > $3))
             ORDER BY lower(name) ASC, id ASC
             LIMIT $4`,
            [input.tenantId, cursor.n, cursor.i, limit],
          )
        : await q<NodeRow>(
            input.tenantId,
            `SELECT * FROM "${schema}".nodes
             WHERE tenant_id = $1 AND deleted_at IS NOT NULL
             ORDER BY lower(name) ASC, id ASC
             LIMIT $2`,
            [input.tenantId, limit],
          );
      const items = res.rows.map(rowToFileNode);
      return ok({ items, nextCursor: pageCursor(items, limit) });
    },

    async scanFileKeys(input) {
      await ensureInitialized();
      const res = await q<{ id: string; s3_key: string }>(
        input.tenantId,
        `SELECT id, s3_key FROM "${schema}".nodes
         WHERE tenant_id = $1 AND deleted_at IS NULL AND kind = 'file' AND s3_key <> ''`,
        [input.tenantId],
      );
      return ok(res.rows.map((r) => ({ id: r.id, s3Key: r.s3_key })));
    },

    async sumSize(input) {
      await ensureInitialized();
      const res = await q<{ c: string }>(
        input.tenantId,
        `SELECT COALESCE(SUM(size), 0)::text AS c FROM "${schema}".nodes
         WHERE tenant_id = $1 AND deleted_at IS NULL AND kind = 'file'`,
        [input.tenantId],
      );
      return ok(Number.parseInt(res.rows[0]?.c ?? "0", 10));
    },

    async findByS3Key(input) {
      await ensureInitialized();
      const res = await q<NodeRow>(
        input.tenantId,
        `SELECT * FROM "${schema}".nodes
         WHERE tenant_id = $1 AND s3_key = $2 AND deleted_at IS NULL
         LIMIT 1`,
        [input.tenantId, input.s3Key],
      );
      return ok(res.rows[0] ? rowToFileNode(res.rows[0]) : null);
    },

    async createShare(input) {
      await ensureInitialized();
      const node = await q<NodeRow>(
        input.tenantId,
        `SELECT * FROM "${schema}".nodes
         WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL`,
        [input.nodeId, input.tenantId],
      );
      if (!node.rows[0]) return notFound(input.nodeId);
      const token = makeId();
      await q(
        input.tenantId,
        `INSERT INTO "${schema}".shares (token, tenant_id, node_id, expires_at)
         VALUES ($1, $2, $3, $4)`,
        [token, input.tenantId, input.nodeId, input.expiresAt ?? null],
      );
      return ok({ token });
    },

    async resolveShare(input) {
      await ensureInitialized();
      const share = await pool.query<{
        tenant_id: string;
        node_id: string;
        expires_at: Date | null;
      }>(
        `SELECT tenant_id, node_id, expires_at FROM "${schema}".shares WHERE token = $1`,
        [input.token],
      );
      const row = share.rows[0];
      if (!row) return ok(null);
      if (row.expires_at && row.expires_at.getTime() < Date.now()) return ok(null);
      const node = await q<NodeRow>(
        row.tenant_id,
        `SELECT * FROM "${schema}".nodes
         WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL`,
        [row.node_id, row.tenant_id],
      );
      return ok(node.rows[0] ? rowToFileNode(node.rows[0]) : null);
    },

    async revokeShare(input) {
      await ensureInitialized();
      const result = await pool.query(
        `DELETE FROM "${schema}".shares WHERE token = $1 AND tenant_id = $2`,
        [input.token, input.tenantId],
      );
      if (result.rowCount === 0) {
        return err(
          new FileSystemError({
            code: "NotFound",
            message: `Share ${input.token} not found`,
            retryable: false,
          }),
        );
      }
      return ok(undefined);
    },
  };
};

export { asTenantId, asUserId };
