/**
 * `createPostgresStore` — a Postgres-backed `MetadataStore`.
 *
 * Built on `pg` (node-postgres). Public methods are async (the
 * interface requires it); the actual SQL runs against a `Pool`
 * whose connections are managed internally.
 *
 * Schema (one table):
 *
 *   nodes(
 *     id          UUID PRIMARY KEY,        -- generated by the app
 *     tenant_id   TEXT NOT NULL,
 *     parent_id   UUID,                    -- NULL = root
 *     name        TEXT NOT NULL,
 *     path        TEXT NOT NULL,           -- materialized "/a/b/c"
 *     kind        TEXT NOT NULL CHECK (kind IN ('file','folder')),
 *     size        BIGINT NOT NULL DEFAULT 0,
 *     mime_type   TEXT NOT NULL DEFAULT '',
 *     s3_key      TEXT NOT NULL DEFAULT '',
 *     owner_id    TEXT NOT NULL,
 *     metadata    JSONB NOT NULL DEFAULT '{}'::jsonb,
 *     created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
 *     updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
 *     deleted_at  TIMESTAMPTZ
 *   )
 *
 * Two partial unique indexes for name uniqueness (Postgres treats
 * NULL as distinct in UNIQUE indexes, same footgun as SQLite):
 *
 *   - (tenant_id, parent_id, name) WHERE deleted_at IS NULL
 *     AND parent_id IS NOT NULL  → non-root siblings
 *   - (tenant_id, name) WHERE deleted_at IS NULL
 *     AND parent_id IS NULL      → root children
 *
 * Indexes for hot paths:
 *   nodes_path_prefix  → LIKE 'path/%' for moveNode cascade
 *   nodes_tenant_parent → listChildren
 *   nodes_name_lower   → ILIKE search
 *
 * Tenant isolation is enforced in app code (every query filters
 * by tenant_id). For a stricter setup, RLS policies + a per-query
 * `SET LOCAL app.current_tenant` would close the gap at the DB.
 * Tracked for a follow-up.
 *
 * The `reconcile()` method is a no-op scan — same as the memory
 * and SQLite stores. Real bucket-walking reconcile would need
 * the S3 adapter injected into the store, which would change the
 * interface. Deferred to a follow-up.
 */
import { createRequire } from "node:module";
import type { Pool, PoolClient, QueryResultRow } from "pg";

/**
 * Lazy-load `pg` (node-postgres). The native modules (pg's optional
 * native bindings) and connection management shouldn't enter
 * every consumer's bundle. Same pattern as `sqlite-store.ts`.
 */
type PgModule = typeof import("pg");
type PgTypes = {
  Pool: new (opts: { connectionString: string; max?: number }) => Pool;
  PoolClient: new (...args: never[]) => PoolClient;
  QueryResultRow: QueryResultRow;
};
const extractPg = (mod: PgModule): PgTypes => {
  const m = mod as unknown as { default?: PgTypes };
  return m.default ?? (mod as unknown as PgTypes);
};
import {
  err,
  ok,
  type Result,
} from "@/types/result";
import { FileSystemError } from "@/errors";
import { asS3Key, asTenantId, asUserId } from "@/types/branded";
import type {
  CreateNodeInput,
  DeleteNodeInput,
  FileNode,
  GetNodeInput,
  GetPathInput,
  ListChildrenInput,
  ListChildrenOutput,
  MetadataStore,
  MoveNodeInput,
  ReconcileResult,
  SearchInput,
  UpdateMetadataInput,
} from "./store";

// ---------------------------------------------------------------------------
// Options
// ---------------------------------------------------------------------------

export interface PostgresStoreOptions {
  /**
   * A libpq connection string. Example:
   *   postgres://user:pass@localhost:5432/dbname
   */
  readonly connectionString: string;
  /**
   * Postgres schema (namespace). Defaults to "public".
   * Use a dedicated schema per tenant in shared clusters.
   */
  readonly schema?: string;
  /**
   * Run schema migrations on construction. Default: true.
   */
  readonly runMigrations?: boolean;
  /**
   * Max pool size. Defaults to 10.
   */
  readonly maxPoolSize?: number;
}

// ---------------------------------------------------------------------------
// Row → FileNode
// ---------------------------------------------------------------------------

interface NodeRow extends QueryResultRow {
  readonly id: string;
  readonly tenant_id: string;
  readonly parent_id: string | null;
  readonly name: string;
  readonly path: string;
  readonly kind: "file" | "folder";
  readonly size: string | number;
  readonly mime_type: string;
  readonly s3_key: string;
  readonly owner_id: string;
  readonly metadata: Record<string, string>;
  readonly created_at: Date;
  readonly updated_at: Date;
  readonly deleted_at: Date | null;
}

interface OrphanRow {
  readonly id: string;
  readonly tenant_id: string;
  readonly s3_key: string;
  readonly metadata_id: string | null;
  readonly reason: string;
  readonly created_at: Date;
}

const rowToPendingOrphan = (row: OrphanRow) => ({
  id: row.id,
  tenantId: asTenantId(row.tenant_id),
  s3Key: asS3Key(row.s3_key),
  metadataId: row.metadata_id,
  reason: row.reason,
  createdAt: row.created_at,
});

const rowToFileNode = (row: NodeRow): FileNode => ({
  id: row.id,
  tenantId: asTenantId(row.tenant_id),
  parentId: row.parent_id,
  name: row.name,
  path: row.path,
  kind: row.kind,
  // pg returns BIGINT as string by default to avoid precision loss
  // on JS numbers > 2^53. Cast back; file sizes fit comfortably.
  size: typeof row.size === "string" ? Number.parseInt(row.size, 10) : row.size,
  mimeType: row.mime_type,
  s3Key: row.s3_key,
  ownerId: asUserId(row.owner_id),
  metadata: row.metadata,
  createdAt: row.created_at,
  updatedAt: row.updated_at,
  deletedAt: row.deleted_at,
});

// ---------------------------------------------------------------------------
// Migrations
// ---------------------------------------------------------------------------

const SCHEMA_VERSION = 2;

const MIGRATION_SQL = (schema: string): string => `
CREATE SCHEMA IF NOT EXISTS "${schema}";

-- Tables are schema-qualified (they have to be, to live in
-- the schema). Index NAMES must NOT be schema-qualified —
-- Postgres syntax error otherwise. The index inherits the
-- schema from its table, so search_path isn't required.

CREATE TABLE IF NOT EXISTS "${schema}".schema_meta (
  key   TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "${schema}".nodes (
  id          UUID PRIMARY KEY,
  tenant_id   TEXT NOT NULL,
  parent_id   UUID,
  name        TEXT NOT NULL,
  path        TEXT NOT NULL,
  kind        TEXT NOT NULL CHECK (kind IN ('file', 'folder')),
  size        BIGINT NOT NULL DEFAULT 0,
  mime_type   TEXT NOT NULL DEFAULT '',
  s3_key      TEXT NOT NULL DEFAULT '',
  owner_id    TEXT NOT NULL,
  metadata    JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at  TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "${schema}".pending_orphans (
  id          UUID PRIMARY KEY,
  tenant_id   TEXT NOT NULL,
  s3_key      TEXT NOT NULL,
  metadata_id TEXT,
  reason      TEXT NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS pending_orphans_tenant_created
  ON "${schema}".pending_orphans (tenant_id, created_at);

-- Name uniqueness for non-root siblings.
CREATE UNIQUE INDEX IF NOT EXISTS nodes_unique_live_nonroot_name
  ON "${schema}".nodes (tenant_id, parent_id, name)
  WHERE deleted_at IS NULL AND parent_id IS NOT NULL;

-- Name uniqueness for root children (NULL parent_id).
CREATE UNIQUE INDEX IF NOT EXISTS nodes_unique_live_root_name
  ON "${schema}".nodes (tenant_id, name)
  WHERE deleted_at IS NULL AND parent_id IS NULL;

CREATE INDEX IF NOT EXISTS nodes_path_prefix
  ON "${schema}".nodes (path text_pattern_ops);
CREATE INDEX IF NOT EXISTS nodes_tenant_parent
  ON "${schema}".nodes (tenant_id, parent_id);
CREATE INDEX IF NOT EXISTS nodes_name_lower
  ON "${schema}".nodes (lower(name));
`;

const runMigrations = async (
  pool: Pool,
  schema: string,
): Promise<void> => {
  const client = await pool.connect();
  try {
    await client.query(MIGRATION_SQL(schema));
    await client.query(
      `INSERT INTO "${schema}".schema_meta (key, value) VALUES ('version', $1)
       ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value`,
      [String(SCHEMA_VERSION)],
    );
  } finally {
    client.release();
  }
};

// ---------------------------------------------------------------------------
// Factory
// ---------------------------------------------------------------------------

export const createPostgresStore = (
  options: PostgresStoreOptions,
): MetadataStore => {
  // Public factory is sync; the real work builds lazily on first
  // method call. See the matching comment in sqlite-store.ts.
  let inner: MetadataStore | null = null;
  let pending: Promise<MetadataStore> | null = null;

  const ensureReady = async (): Promise<MetadataStore> => {
    if (inner) return inner;
    if (!pending) {
      pending = (async () => {
        const req = createRequire(import.meta.url);
        const mod = req("pg") as PgModule;
        inner = buildInner(extractPg(mod), options);
        return inner;
      })();
    }
    return pending;
  };

  const wrap = <A extends unknown[], R>(
    method: (store: MetadataStore, ...args: A) => Promise<R>,
  ): ((...args: A) => Promise<R>) =>
    async (...args: A): Promise<R> => {
      const s = await ensureReady();
      return method(s, ...args);
    };

  return {
    createNode: wrap((s, i) => s.createNode(i)),
    getNode: wrap((s, i) => s.getNode(i)),
    listChildren: wrap((s, i) => s.listChildren(i)),
    moveNode: wrap((s, i) => s.moveNode(i)),
    deleteNode: wrap((s, i) => s.deleteNode(i)),
    updateMetadata: wrap((s, i) => s.updateMetadata(i)),
    search: wrap((s, i) => s.search(i)),
    getPath: wrap((s, i) => s.getPath(i)),
    reconcile: wrap((s) => s.reconcile()),
    enqueueOrphan: wrap((s, i) => s.enqueueOrphan(i)),
    listPendingOrphans: wrap((s, i) => s.listPendingOrphans(i)),
    deleteOrphan: wrap((s, i) => s.deleteOrphan(i)),
  };
};

/**
 * Real factory — builds the prepared-query store using the loaded
 * pg module.
 */
const buildInner = (pg: PgTypes, options: PostgresStoreOptions): MetadataStore => {
  const pool = new pg.Pool({
    connectionString: options.connectionString,
    max: options.maxPoolSize ?? 10,
  });
  const schema = options.schema ?? "public";

  // Lazy migrations on first method call — keeps the factory
  // synchronous (the MetadataStore contract is async per method).
  let initPromise: Promise<void> | null = null;
  const ensureInitialized = async (): Promise<void> => {
    if (!initPromise) {
      initPromise =
        options.runMigrations === false
          ? Promise.resolve()
          : runMigrations(pool, schema);
    }
    return initPromise;
  };

  // -------------------------------------------------------------------------
  // Helpers
  // -------------------------------------------------------------------------

  const makeId = (): string => {
    if (typeof globalThis.crypto?.randomUUID === "function") {
      return globalThis.crypto.randomUUID();
    }
    return `pg-${Date.now()}-${Math.random().toString(36).slice(2, 10)}`;
  };

  const notFound = (id: string): Result<never, FileSystemError> =>
    err(
      new FileSystemError({
        code: "NotFound",
        message: `Node ${id} not found`,
        retryable: false,
      }),
    );

  // LIKE escape: `\` first, then `%` and `_` (must match the ESCAPE
  // clause in the SQL).
  const escapeLike = (s: string): string =>
    s.replace(/\\/g, "\\\\").replace(/%/g, "\\%").replace(/_/g, "\\_");

  // Wrap a query in a transaction. Caller provides the work as an
  // async function; on success the tx commits, on throw it rolls back.
  const withTx = async <T>(fn: (c: PoolClient) => Promise<T>): Promise<T> => {
    const client = await pool.connect();
    try {
      await client.query("BEGIN");
      const result = await fn(client);
      await client.query("COMMIT");
      return result;
    } catch (e) {
      await client.query("ROLLBACK").catch(() => {
        // Ignore rollback errors — the original error is more useful.
      });
      throw e;
    } finally {
      client.release();
    }
  };

  // -------------------------------------------------------------------------
  // 9-method contract
  // -------------------------------------------------------------------------

  return {
    async createNode(
      input: CreateNodeInput,
    ): Promise<Result<FileNode, FileSystemError>> {
      await ensureInitialized();
      // Look up parent (if any) to compute the path. We require
      // a LIVE parent; tombstoned parents can't have new children.
      // `!= null` so BOTH null and undefined skip the lookup.
      let parentPath: string | null = null;
      if (input.parentId != null) {
        const parentRes = await pool.query<NodeRow>(
          `SELECT * FROM "${schema}".nodes
           WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL`,
          [input.parentId, input.tenantId],
        );
        const parent = parentRes.rows[0];
        if (!parent) return notFound(input.parentId);
        if (parent.kind !== "folder") {
          return err(
            new FileSystemError({
              code: "Conflict",
              message: `Parent ${input.parentId} is not a folder`,
              retryable: false,
            }),
          );
        }
        parentPath = parent.path;
      }

      const id = makeId();
      const path = parentPath === null ? `/${input.name}` : `${parentPath}/${input.name}`;

      try {
        await pool.query(
          `INSERT INTO "${schema}".nodes (
            id, tenant_id, parent_id, name, path, kind, size, mime_type,
            s3_key, owner_id, metadata
          ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11::jsonb)`,
          [
            id,
            input.tenantId,
            input.parentId,
            input.name,
            path,
            input.kind,
            input.kind === "folder" ? 0 : input.size,
            input.kind === "folder" ? "" : input.mimeType,
            input.kind === "folder" ? "" : input.s3Key,
            input.ownerId,
            JSON.stringify(input.metadata ?? {}),
          ],
        );
      } catch (e) {
        if (e instanceof Error && /nodes_unique_live/.test(e.message)) {
          return err(
            new FileSystemError({
              code: "Conflict",
              message: `A node named '${input.name}' already exists in this folder`,
              retryable: false,
            }),
          );
        }
        return err(
          new FileSystemError({
            code: "InternalError",
            message: `createNode failed: ${(e as Error).message}`,
            retryable: false,
          }),
        );
      }

      const created = await pool.query<NodeRow>(
        `SELECT * FROM "${schema}".nodes WHERE id = $1 AND tenant_id = $2`,
        [id, input.tenantId],
      );
      if (created.rows.length === 0) {
        return err(
          new FileSystemError({
            code: "InternalError",
            message: "Row missing immediately after insert",
            retryable: false,
          }),
        );
      }
      return ok(rowToFileNode(created.rows[0]!));
    },

    async getNode(
      input: GetNodeInput,
    ): Promise<Result<FileNode | null, FileSystemError>> {
      await ensureInitialized();
      const res = await pool.query<NodeRow>(
        `SELECT * FROM "${schema}".nodes
         WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL`,
        [input.id, input.tenantId],
      );
      return ok(res.rows[0] ? rowToFileNode(res.rows[0]) : null);
    },

    async listChildren(
      input: ListChildrenInput,
    ): Promise<Result<ListChildrenOutput, FileSystemError>> {
      await ensureInitialized();
      const limit = input.limit ?? 1000;
      const res = await pool.query<NodeRow>(
        `SELECT * FROM "${schema}".nodes
         WHERE tenant_id = $1 AND parent_id IS NOT DISTINCT FROM $2
           AND deleted_at IS NULL
         ORDER BY lower(name) ASC
         LIMIT $3`,
        [input.tenantId, input.parentId, limit],
      );
      return ok({
        items: res.rows.map(rowToFileNode),
        nextCursor: res.rows.length === limit ? String(limit) : undefined,
      });
    },

    async moveNode(
      input: MoveNodeInput,
    ): Promise<Result<FileNode, FileSystemError>> {
      await ensureInitialized();
      const currentRes = await pool.query<NodeRow>(
        `SELECT * FROM "${schema}".nodes
         WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL`,
        [input.id, input.tenantId],
      );
      const current = currentRes.rows[0];
      if (!current) return notFound(input.id);

      const newName = input.newName ?? current.name;

      // Validate the new parent (if any). `!= null` (NOT `!== null`)
      // so both null and undefined skip the block.
      let newParentPath: string | null = null;
      if (input.newParentId != null) {
        if (input.newParentId === current.id) {
          return err(
            new FileSystemError({
              code: "Conflict",
              message: "Cannot move a folder into itself",
              retryable: false,
            }),
          );
        }
        const newParentRes = await pool.query<NodeRow>(
          `SELECT * FROM "${schema}".nodes
           WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL`,
          [input.newParentId, input.tenantId],
        );
        const newParent = newParentRes.rows[0];
        if (!newParent) return notFound(input.newParentId);
        if (newParent.kind !== "folder") {
          return err(
            new FileSystemError({
              code: "Conflict",
              message: `Destination ${input.newParentId} is not a folder`,
              retryable: false,
            }),
          );
        }
        // Cycle: newParent must not be a descendant of current.
        if (
          newParent.path === current.path ||
          newParent.path.startsWith(`${current.path}/`)
        ) {
          return err(
            new FileSystemError({
              code: "Conflict",
              message: "Cannot move a folder into its own descendant",
              retryable: false,
            }),
          );
        }
        newParentPath = newParent.path;
      }

      const newPath =
        newParentPath === null ? `/${newName}` : `${newParentPath}/${newName}`;

      try {
        await withTx(async (client) => {
          await client.query(
            `UPDATE "${schema}".nodes
             SET parent_id = $1, name = $2, path = $3, updated_at = now()
             WHERE id = $4`,
            [input.newParentId, newName, newPath, input.id],
          );
          if (current.path !== newPath) {
            // Prefix-only replace via substring — same trick as
            // the SQLite store, but using Postgres substring()
            // (1-indexed). SUBSTR's LENGTH on the old path + 1
            // gives the position of the leading '/' in the
            // descendant path.
            await client.query(
              `UPDATE "${schema}".nodes
               SET path = $1 || substring(path FROM length($2) + 1),
                   updated_at = now()
               WHERE path LIKE $2 || '/%'`,
              [newPath, current.path],
            );
          }
        });
      } catch (e) {
        if (e instanceof Error && /nodes_unique_live/.test(e.message)) {
          return err(
            new FileSystemError({
              code: "Conflict",
              message: `A node named '${newName}' already exists in the destination folder`,
              retryable: false,
            }),
          );
        }
        return err(
          new FileSystemError({
            code: "InternalError",
            message: `moveNode failed: ${(e as Error).message}`,
            retryable: false,
          }),
        );
      }

      const updated = await pool.query<NodeRow>(
        `SELECT * FROM "${schema}".nodes
         WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL`,
        [input.id, input.tenantId],
      );
      if (updated.rows.length === 0) {
        return err(
          new FileSystemError({
            code: "InternalError",
            message: "Node missing after move",
            retryable: false,
          }),
        );
      }
      return ok(rowToFileNode(updated.rows[0]!));
    },

    async deleteNode(
      input: DeleteNodeInput,
    ): Promise<Result<void, FileSystemError>> {
      await ensureInitialized();
      const nodeRes = await pool.query<NodeRow>(
        `SELECT * FROM "${schema}".nodes
         WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL`,
        [input.id, input.tenantId],
      );
      const node = nodeRes.rows[0];
      if (!node) return notFound(input.id);

      if (node.kind === "folder" && !input.recursive) {
        const childRes = await pool.query(
          `SELECT 1 FROM "${schema}".nodes
           WHERE tenant_id = $1 AND parent_id = $2 AND deleted_at IS NULL
           LIMIT 1`,
          [input.tenantId, input.id],
        );
        if (childRes.rows.length > 0) {
          return err(
            new FileSystemError({
              code: "Conflict",
              message: `Folder '${node.name}' is not empty; pass recursive: true to delete the subtree`,
              retryable: false,
            }),
          );
        }
      }

      if (input.recursive || node.kind === "file") {
        await pool.query(
          `UPDATE "${schema}".nodes
           SET deleted_at = now(), updated_at = now()
           WHERE (id = $1 OR path LIKE $2 || '/%')
             AND deleted_at IS NULL`,
          [input.id, node.path],
        );
      } else {
        await pool.query(
          `UPDATE "${schema}".nodes
           SET deleted_at = now(), updated_at = now()
           WHERE id = $1`,
          [input.id],
        );
      }
      return ok(undefined);
    },

    async updateMetadata(
      input: UpdateMetadataInput,
    ): Promise<Result<FileNode, FileSystemError>> {
      await ensureInitialized();
      const exists = await pool.query(
        `SELECT 1 FROM "${schema}".nodes
         WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL`,
        [input.id, input.tenantId],
      );
      if (exists.rows.length === 0) return notFound(input.id);

      // Replace or merge via JSONB concat. The `||` operator
      // merges with right-hand keys winning on conflict.
      const sql = input.replace
        ? `UPDATE "${schema}".nodes
           SET metadata = $1::jsonb, updated_at = now()
           WHERE id = $2 AND tenant_id = $3`
        : `UPDATE "${schema}".nodes
           SET metadata = metadata || $1::jsonb, updated_at = now()
           WHERE id = $2 AND tenant_id = $3`;
      await pool.query(sql, [
        JSON.stringify(input.metadata),
        input.id,
        input.tenantId,
      ]);

      const updated = await pool.query<NodeRow>(
        `SELECT * FROM "${schema}".nodes WHERE id = $1 AND tenant_id = $2`,
        [input.id, input.tenantId],
      );
      if (updated.rows.length === 0) return notFound(input.id);
      return ok(rowToFileNode(updated.rows[0]!));
    },

    async search(
      input: SearchInput,
    ): Promise<Result<ListChildrenOutput, FileSystemError>> {
      await ensureInitialized();
      const limit = input.limit ?? 100;

      // Empty query → no results (v0.2 contract). Without this,
      // `ILIKE '%%'` would match every node in the tenant.
      if (input.query.length === 0) {
        return ok({ items: [], nextCursor: undefined });
      }

      const pattern = `%${escapeLike(input.query)}%`;

      let res;
      if (input.parentId === undefined) {
        // No scope: search the whole tenant.
        res = await pool.query<NodeRow>(
          `SELECT * FROM "${schema}".nodes
           WHERE tenant_id = $1 AND deleted_at IS NULL
             AND name ILIKE $2 ESCAPE '\\'
           ORDER BY lower(name) ASC
           LIMIT $3`,
          [input.tenantId, pattern, limit],
        );
      } else {
        const parentRes = await pool.query<NodeRow>(
          `SELECT * FROM "${schema}".nodes
           WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL`,
          [input.parentId, input.tenantId],
        );
        const parent = parentRes.rows[0];
        if (!parent) return notFound(input.parentId);
        // Root's subtree is the whole tenant — use the unscoped query.
        if (parent.path === "/") {
          res = await pool.query<NodeRow>(
            `SELECT * FROM "${schema}".nodes
             WHERE tenant_id = $1 AND deleted_at IS NULL
               AND name ILIKE $2 ESCAPE '\\'
             ORDER BY lower(name) ASC
             LIMIT $3`,
            [input.tenantId, pattern, limit],
          );
        } else {
          res = await pool.query<NodeRow>(
            `SELECT * FROM "${schema}".nodes
             WHERE tenant_id = $1 AND deleted_at IS NULL
               AND (id = $2 OR path LIKE $3 || '/%')
               AND name ILIKE $4 ESCAPE '\\'
             ORDER BY lower(name) ASC
             LIMIT $5`,
            [input.tenantId, input.parentId, parent.path, pattern, limit],
          );
        }
      }
      return ok({
        items: res.rows.map(rowToFileNode),
        nextCursor: res.rows.length === limit ? String(limit) : undefined,
      });
    },

    async getPath(
      input: GetPathInput,
    ): Promise<Result<{ segments: FileNode[] }, FileSystemError>> {
      await ensureInitialized();
      // Recursive CTE walks up the parent chain in one query.
      // Includes tombstoned ancestors to match the memory/SQLite
      // behavior (no gaps even if a mid-chain parent is deleted).
      const res = await pool.query<NodeRow>(
        `WITH RECURSIVE chain AS (
           SELECT * FROM "${schema}".nodes
            WHERE id = $1 AND tenant_id = $2
           UNION ALL
           SELECT n.* FROM "${schema}".nodes n
             JOIN chain c ON n.id = c.parent_id
            WHERE n.tenant_id = $2
         )
         SELECT * FROM chain ORDER BY path ASC`,
        [input.id, input.tenantId],
      );
      if (res.rows.length === 0) return notFound(input.id);
      return ok({ segments: res.rows.map(rowToFileNode) });
    },

    async enqueueOrphan(input) {
      await ensureInitialized();
      const id = makeId();
      try {
        await pool.query(
          `INSERT INTO "${schema}".pending_orphans (
             id, tenant_id, s3_key, metadata_id, reason
           ) VALUES ($1, $2, $3, $4, $5)`,
          [
            id,
            input.tenantId,
            input.s3Key,
            input.metadataId ?? null,
            input.reason,
          ],
        );
        return ok({ id });
      } catch (error) {
        return err(FileSystemError.fromPg(error));
      }
    },

    async listPendingOrphans(input) {
      await ensureInitialized();
      try {
        const result = await pool.query<OrphanRow>(
          `SELECT * FROM "${schema}".pending_orphans
           WHERE tenant_id = $1
           ORDER BY created_at ASC, id ASC`,
          [input.tenantId],
        );
        return ok(result.rows.map(rowToPendingOrphan));
      } catch (error) {
        return err(FileSystemError.fromPg(error));
      }
    },

    async deleteOrphan(input) {
      await ensureInitialized();
      try {
        const result = await pool.query(
          `DELETE FROM "${schema}".pending_orphans
           WHERE tenant_id = $1 AND id = $2`,
          [input.tenantId, input.id],
        );
        if (result.rowCount === 0) {
          return err(
            new FileSystemError({
              code: "NotFound",
              message: `Orphan ${input.id} not found`,
              retryable: false,
            }),
          );
        }
        return ok(undefined);
      } catch (error) {
        return err(FileSystemError.fromPg(error));
      }
    },

    async reconcile(): Promise<Result<ReconcileResult, FileSystemError>> {
      await ensureInitialized();
      // No-op: real bucket-walking reconcile needs the S3
      // adapter injected, which would change the MetadataStore
      // interface. Deferred to a follow-up.
      const res = await pool.query<{ c: string }>(
        `SELECT count(*)::text AS c FROM "${schema}".nodes WHERE deleted_at IS NULL`,
      );
      return ok({
        orphansInStore: [],
        orphansInS3: [],
        scanned: Number.parseInt(res.rows[0]?.c ?? "0", 10),
      });
    },
  };
};

export { asTenantId, asUserId };
